### ISSUE TITLE
Paket

### ISSUE THREAD

**Issue by reach4thelasers** [marcinbudny/applicationinsights-owinextensions#2] opened 2016-07-27 15:44 UTC
Seems like a good library you've made.  Unfortunately I can't say the same for the package manager you've chosen.  I've been trying to restore packages for over an hour and have given up.

**Comment by marcinbudny** [comment] 2016-07-27 16:49
Hi Kevin,
Sorry to hear that. Actually I have noticed this problem some time ago, but never got around to fix it. It's actually my fault, not the package manager's. I suppose this is what you get when you are too lazy to do a proper CI. Maybe I'll find some time over the weekend to fix this.

As a temp workaround you could remove the TestWebsite project from the solution in order to compile it and run the unit/integration tests. So the sequence of steps should be.

0. Clone repo, open powershell in the folder
0. `cd src`
0. `.\.paket\paket.bootstrapper.exe`
0. `.\.paket\paket.exe install`
0. Open solution in VS, remove TestWebsite, compile & run tests

**Comment by marcinbudny** [comment] 2016-07-30 14:25
The problem is now fixed in ac3253620c885556ab44faab5e7dbb87ce5325ff

**Closed** 2016-07-30 14:32 UTC
